#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrOps
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PrinterOps")]
	public partial class DataClassesPODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesPODataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PrinterOpsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_ChargeCartridge> t_ChargeCartridges
		{
			get
			{
				return this.GetTable<t_ChargeCartridge>();
			}
		}
		
		public System.Data.Linq.Table<t_PrinterState> t_PrinterStates
		{
			get
			{
				return this.GetTable<t_PrinterState>();
			}
		}
		
		public System.Data.Linq.Table<t_BranchSerial> t_BranchSerials
		{
			get
			{
				return this.GetTable<t_BranchSerial>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_YMD")]
		public ISingleResult<sp_SEL_YMDResult> sp_SEL_YMD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="Int")] System.Nullable<int> yEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTH", DbType="Int")] System.Nullable<int> mONTH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DAY", DbType="Int")] System.Nullable<int> dAY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yEAR, mONTH, dAY);
			return ((ISingleResult<sp_SEL_YMDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_BRANCH")]
		public ISingleResult<sp_SEL_BRANCHResult> sp_SEL_BRANCH()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SEL_BRANCHResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_YMB")]
		public ISingleResult<sp_SEL_YMBResult> sp_SEL_YMB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Year", DbType="Int")] System.Nullable<int> year, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Month", DbType="Int")] System.Nullable<int> month, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BRANCH", DbType="VarChar(5)")] string bRANCH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), year, month, bRANCH);
			return ((ISingleResult<sp_SEL_YMBResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_YMDB")]
		public ISingleResult<sp_SEL_YMDBResult> sp_SEL_YMDB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="Int")] System.Nullable<int> yEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTH", DbType="Int")] System.Nullable<int> mONTH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DAY", DbType="Int")] System.Nullable<int> dAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BRANCH", DbType="VarChar(5)")] string bRANCH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yEAR, mONTH, dAY, bRANCH);
			return ((ISingleResult<sp_SEL_YMDBResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_YM")]
		public ISingleResult<sp_SEL_YMResult> sp_SEL_YM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="Int")] System.Nullable<int> yEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTH", DbType="Int")] System.Nullable<int> mONTH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yEAR, mONTH);
			return ((ISingleResult<sp_SEL_YMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_YM_TOTAL")]
		public ISingleResult<sp_SEL_YM_TOTALResult> sp_SEL_YM_TOTAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="Int")] System.Nullable<int> yEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTH", DbType="Int")] System.Nullable<int> mONTH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yEAR, mONTH);
			return ((ISingleResult<sp_SEL_YM_TOTALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_YMB_TOTAL")]
		public ISingleResult<sp_SEL_YMB_TOTALResult> sp_SEL_YMB_TOTAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Year", DbType="Int")] System.Nullable<int> year, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Month", DbType="Int")] System.Nullable<int> month, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BRANCH", DbType="VarChar(5)")] string bRANCH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), year, month, bRANCH);
			return ((ISingleResult<sp_SEL_YMB_TOTALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_YMD_TOTAL")]
		public ISingleResult<sp_SEL_YMD_TOTALResult> sp_SEL_YMD_TOTAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="Int")] System.Nullable<int> yEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTH", DbType="Int")] System.Nullable<int> mONTH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DAY", DbType="Int")] System.Nullable<int> dAY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yEAR, mONTH, dAY);
			return ((ISingleResult<sp_SEL_YMD_TOTALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_YMDB_TOTAL")]
		public ISingleResult<sp_SEL_YMDB_TOTALResult> sp_SEL_YMDB_TOTAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="Int")] System.Nullable<int> yEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTH", DbType="Int")] System.Nullable<int> mONTH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DAY", DbType="Int")] System.Nullable<int> dAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BRANCH", DbType="VarChar(5)")] string bRANCH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yEAR, mONTH, dAY, bRANCH);
			return ((ISingleResult<sp_SEL_YMDB_TOTALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_LOAD_Y")]
		public ISingleResult<sp_SEL_LOAD_YResult> sp_SEL_LOAD_Y([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="Int")] System.Nullable<int> yEAR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yEAR);
			return ((ISingleResult<sp_SEL_LOAD_YResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_LOAD_YM")]
		public ISingleResult<sp_SEL_LOAD_YMResult> sp_SEL_LOAD_YM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="Int")] System.Nullable<int> yEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTH", DbType="Int")] System.Nullable<int> mONTH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yEAR, mONTH);
			return ((ISingleResult<sp_SEL_LOAD_YMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_PrinterState")]
		public ISingleResult<sp_SEL_PrinterStateResult> sp_SEL_PrinterState()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SEL_PrinterStateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_USBPrinterState")]
		public ISingleResult<sp_SEL_USBPrinterStateResult> sp_SEL_USBPrinterState()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SEL_USBPrinterStateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_PercentToner", IsComposable=true)]
		public System.Nullable<int> fn_PercentToner([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaxLevel", DbType="Int")] System.Nullable<int> maxLevel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remaining", DbType="Int")] System.Nullable<int> remaining)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maxLevel, remaining).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_RemainDays")]
		public ISingleResult<sp_SEL_RemainDaysResult> sp_SEL_RemainDays()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SEL_RemainDaysResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_MERGE_BranchSerial")]
		public int sp_MERGE_BranchSerial([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BranchNumber", DbType="NVarChar(20)")] string branchNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SerialNumber", DbType="NVarChar(50)")] string serialNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), branchNumber, serialNumber);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_RemainDays2")]
		public ISingleResult<sp_SEL_RemainDays2Result> sp_SEL_RemainDays2()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SEL_RemainDays2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SEL_TONER")]
		public ISingleResult<sp_SEL_TONERResult> sp_SEL_TONER()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SEL_TONERResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_ChargeCartridge")]
	public partial class t_ChargeCartridge
	{
		
		private string _SerialNumber;
		
		private int _OldRemainToner;
		
		private int _PageCount;
		
		private System.DateTime _ChargeDate;
		
		private int _NewRemainToner;
		
		private string _ColorToner;
		
		public t_ChargeCartridge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldRemainToner", DbType="Int NOT NULL")]
		public int OldRemainToner
		{
			get
			{
				return this._OldRemainToner;
			}
			set
			{
				if ((this._OldRemainToner != value))
				{
					this._OldRemainToner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageCount", DbType="Int NOT NULL")]
		public int PageCount
		{
			get
			{
				return this._PageCount;
			}
			set
			{
				if ((this._PageCount != value))
				{
					this._PageCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargeDate", DbType="Date NOT NULL")]
		public System.DateTime ChargeDate
		{
			get
			{
				return this._ChargeDate;
			}
			set
			{
				if ((this._ChargeDate != value))
				{
					this._ChargeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewRemainToner", DbType="Int NOT NULL")]
		public int NewRemainToner
		{
			get
			{
				return this._NewRemainToner;
			}
			set
			{
				if ((this._NewRemainToner != value))
				{
					this._NewRemainToner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorToner", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ColorToner
		{
			get
			{
				return this._ColorToner;
			}
			set
			{
				if ((this._ColorToner != value))
				{
					this._ColorToner = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_PrinterState")]
	public partial class t_PrinterState
	{
		
		private string _SerialNumber;
		
		private string _Model;
		
		private string _IPAddress;
		
		private System.Nullable<int> _PageCount;
		
		private System.Nullable<int> _MaxLevelBlack;
		
		private System.Nullable<int> _RemainBlack;
		
		private System.Nullable<int> _MaxLevelCyan;
		
		private System.Nullable<int> _RemainCyan;
		
		private System.Nullable<int> _MaxLevelMagenta;
		
		private System.Nullable<int> _RemainMagenta;
		
		private System.Nullable<int> _MaxLevelYellow;
		
		private System.Nullable<int> _RemainYellow;
		
		private System.DateTime _LastUpdate;
		
		private string _Uptime;
		
		private string _DisplayMessage;
		
		private string _AlertMessage;
		
		public t_PrinterState()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(50)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageCount", DbType="Int")]
		public System.Nullable<int> PageCount
		{
			get
			{
				return this._PageCount;
			}
			set
			{
				if ((this._PageCount != value))
				{
					this._PageCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelBlack", DbType="Int")]
		public System.Nullable<int> MaxLevelBlack
		{
			get
			{
				return this._MaxLevelBlack;
			}
			set
			{
				if ((this._MaxLevelBlack != value))
				{
					this._MaxLevelBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainBlack", DbType="Int")]
		public System.Nullable<int> RemainBlack
		{
			get
			{
				return this._RemainBlack;
			}
			set
			{
				if ((this._RemainBlack != value))
				{
					this._RemainBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelCyan", DbType="Int")]
		public System.Nullable<int> MaxLevelCyan
		{
			get
			{
				return this._MaxLevelCyan;
			}
			set
			{
				if ((this._MaxLevelCyan != value))
				{
					this._MaxLevelCyan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainCyan", DbType="Int")]
		public System.Nullable<int> RemainCyan
		{
			get
			{
				return this._RemainCyan;
			}
			set
			{
				if ((this._RemainCyan != value))
				{
					this._RemainCyan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelMagenta", DbType="Int")]
		public System.Nullable<int> MaxLevelMagenta
		{
			get
			{
				return this._MaxLevelMagenta;
			}
			set
			{
				if ((this._MaxLevelMagenta != value))
				{
					this._MaxLevelMagenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainMagenta", DbType="Int")]
		public System.Nullable<int> RemainMagenta
		{
			get
			{
				return this._RemainMagenta;
			}
			set
			{
				if ((this._RemainMagenta != value))
				{
					this._RemainMagenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelYellow", DbType="Int")]
		public System.Nullable<int> MaxLevelYellow
		{
			get
			{
				return this._MaxLevelYellow;
			}
			set
			{
				if ((this._MaxLevelYellow != value))
				{
					this._MaxLevelYellow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainYellow", DbType="Int")]
		public System.Nullable<int> RemainYellow
		{
			get
			{
				return this._RemainYellow;
			}
			set
			{
				if ((this._RemainYellow != value))
				{
					this._RemainYellow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this._LastUpdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uptime", DbType="VarChar(50)")]
		public string Uptime
		{
			get
			{
				return this._Uptime;
			}
			set
			{
				if ((this._Uptime != value))
				{
					this._Uptime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayMessage", DbType="VarChar(50)")]
		public string DisplayMessage
		{
			get
			{
				return this._DisplayMessage;
			}
			set
			{
				if ((this._DisplayMessage != value))
				{
					this._DisplayMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertMessage", DbType="VarChar(MAX)")]
		public string AlertMessage
		{
			get
			{
				return this._AlertMessage;
			}
			set
			{
				if ((this._AlertMessage != value))
				{
					this._AlertMessage = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_BranchSerial")]
	public partial class t_BranchSerial
	{
		
		private string _BranchNumber;
		
		private string _SerialNumber;
		
		public t_BranchSerial()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchNumber", DbType="NVarChar(20)")]
		public string BranchNumber
		{
			get
			{
				return this._BranchNumber;
			}
			set
			{
				if ((this._BranchNumber != value))
				{
					this._BranchNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50)")]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_YMDResult
	{
		
		private string _user_name;
		
		private System.Nullable<int> _pages_printed;
		
		public sp_SEL_YMDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(20)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_printed", DbType="Int")]
		public System.Nullable<int> pages_printed
		{
			get
			{
				return this._pages_printed;
			}
			set
			{
				if ((this._pages_printed != value))
				{
					this._pages_printed = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_BRANCHResult
	{
		
		private string _branch;
		
		public sp_SEL_BRANCHResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch", DbType="VarChar(3)")]
		public string branch
		{
			get
			{
				return this._branch;
			}
			set
			{
				if ((this._branch != value))
				{
					this._branch = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_YMBResult
	{
		
		private string _user_name;
		
		private System.Nullable<int> _pages_printed;
		
		public sp_SEL_YMBResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(20)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_printed", DbType="Int")]
		public System.Nullable<int> pages_printed
		{
			get
			{
				return this._pages_printed;
			}
			set
			{
				if ((this._pages_printed != value))
				{
					this._pages_printed = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_YMDBResult
	{
		
		private string _user_name;
		
		private System.Nullable<int> _pages_printed;
		
		public sp_SEL_YMDBResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(20)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_printed", DbType="Int")]
		public System.Nullable<int> pages_printed
		{
			get
			{
				return this._pages_printed;
			}
			set
			{
				if ((this._pages_printed != value))
				{
					this._pages_printed = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_YMResult
	{
		
		private string _user_name;
		
		private System.Nullable<int> _pages_printed;
		
		public sp_SEL_YMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_printed", DbType="Int")]
		public System.Nullable<int> pages_printed
		{
			get
			{
				return this._pages_printed;
			}
			set
			{
				if ((this._pages_printed != value))
				{
					this._pages_printed = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_YM_TOTALResult
	{
		
		private System.Nullable<int> _pages_printed;
		
		public sp_SEL_YM_TOTALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_printed", DbType="Int")]
		public System.Nullable<int> pages_printed
		{
			get
			{
				return this._pages_printed;
			}
			set
			{
				if ((this._pages_printed != value))
				{
					this._pages_printed = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_YMB_TOTALResult
	{
		
		private string _Column1;
		
		private System.Nullable<int> _pages_printed;
		
		public sp_SEL_YMB_TOTALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_printed", DbType="Int")]
		public System.Nullable<int> pages_printed
		{
			get
			{
				return this._pages_printed;
			}
			set
			{
				if ((this._pages_printed != value))
				{
					this._pages_printed = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_YMD_TOTALResult
	{
		
		private System.Nullable<int> _pages_printed;
		
		public sp_SEL_YMD_TOTALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_printed", DbType="Int")]
		public System.Nullable<int> pages_printed
		{
			get
			{
				return this._pages_printed;
			}
			set
			{
				if ((this._pages_printed != value))
				{
					this._pages_printed = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_YMDB_TOTALResult
	{
		
		private System.Nullable<int> _pages_printed;
		
		public sp_SEL_YMDB_TOTALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_printed", DbType="Int")]
		public System.Nullable<int> pages_printed
		{
			get
			{
				return this._pages_printed;
			}
			set
			{
				if ((this._pages_printed != value))
				{
					this._pages_printed = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_LOAD_YResult
	{
		
		private string _SerialNumber;
		
		private string _Model;
		
		private string _printer_name;
		
		private string _IPAddress;
		
		private System.Nullable<int> _PagePrinted;
		
		public sp_SEL_LOAD_YResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50)")]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printer_name", DbType="VarChar(50)")]
		public string printer_name
		{
			get
			{
				return this._printer_name;
			}
			set
			{
				if ((this._printer_name != value))
				{
					this._printer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(50)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagePrinted", DbType="Int")]
		public System.Nullable<int> PagePrinted
		{
			get
			{
				return this._PagePrinted;
			}
			set
			{
				if ((this._PagePrinted != value))
				{
					this._PagePrinted = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_LOAD_YMResult
	{
		
		private string _SerialNumber;
		
		private string _Model;
		
		private string _printer_name;
		
		private string _IPAddress;
		
		private System.Nullable<int> _PagePrinted;
		
		public sp_SEL_LOAD_YMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50)")]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printer_name", DbType="VarChar(50)")]
		public string printer_name
		{
			get
			{
				return this._printer_name;
			}
			set
			{
				if ((this._printer_name != value))
				{
					this._printer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(50)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagePrinted", DbType="Int")]
		public System.Nullable<int> PagePrinted
		{
			get
			{
				return this._PagePrinted;
			}
			set
			{
				if ((this._PagePrinted != value))
				{
					this._PagePrinted = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_PrinterStateResult
	{
		
		private string _printer_name;
		
		private string _SerialNumber;
		
		private string _model;
		
		private string _IPAddress;
		
		private System.Nullable<int> _PageCount;
		
		private System.Nullable<int> _PercentBlack;
		
		private string _DisplayMessage;
		
		private string _AlertMessage;
		
		private string _Uptime;
		
		private System.DateTime _LastUpdate;
		
		public sp_SEL_PrinterStateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printer_name", DbType="VarChar(50)")]
		public string printer_name
		{
			get
			{
				return this._printer_name;
			}
			set
			{
				if ((this._printer_name != value))
				{
					this._printer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(50)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this._model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(50)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageCount", DbType="Int")]
		public System.Nullable<int> PageCount
		{
			get
			{
				return this._PageCount;
			}
			set
			{
				if ((this._PageCount != value))
				{
					this._PageCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PercentBlack", DbType="Int")]
		public System.Nullable<int> PercentBlack
		{
			get
			{
				return this._PercentBlack;
			}
			set
			{
				if ((this._PercentBlack != value))
				{
					this._PercentBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayMessage", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DisplayMessage
		{
			get
			{
				return this._DisplayMessage;
			}
			set
			{
				if ((this._DisplayMessage != value))
				{
					this._DisplayMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertMessage", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string AlertMessage
		{
			get
			{
				return this._AlertMessage;
			}
			set
			{
				if ((this._AlertMessage != value))
				{
					this._AlertMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uptime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Uptime
		{
			get
			{
				return this._Uptime;
			}
			set
			{
				if ((this._Uptime != value))
				{
					this._Uptime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this._LastUpdate = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_USBPrinterStateResult
	{
		
		private string _SerialNumber;
		
		private string _Model;
		
		private System.Nullable<int> _PageCount;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private string _DisplayMessage;
		
		private string _AlertMessage;
		
		private string _ComputerName;
		
		public sp_SEL_USBPrinterStateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageCount", DbType="Int")]
		public System.Nullable<int> PageCount
		{
			get
			{
				return this._PageCount;
			}
			set
			{
				if ((this._PageCount != value))
				{
					this._PageCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this._LastUpdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayMessage", DbType="NVarChar(50)")]
		public string DisplayMessage
		{
			get
			{
				return this._DisplayMessage;
			}
			set
			{
				if ((this._DisplayMessage != value))
				{
					this._DisplayMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertMessage", DbType="NVarChar(MAX)")]
		public string AlertMessage
		{
			get
			{
				return this._AlertMessage;
			}
			set
			{
				if ((this._AlertMessage != value))
				{
					this._AlertMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerName", DbType="NVarChar(50)")]
		public string ComputerName
		{
			get
			{
				return this._ComputerName;
			}
			set
			{
				if ((this._ComputerName != value))
				{
					this._ComputerName = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_RemainDaysResult
	{
		
		private string _Model;
		
		private string _SerialNumber;
		
		private string _IPAddress;
		
		private int _NewRemainToner;
		
		private System.Nullable<int> _MaxLevelBlack;
		
		private System.Nullable<int> _RemainBlack;
		
		private System.Nullable<System.DateTime> _ChargeDate;
		
		public sp_SEL_RemainDaysResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(50)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewRemainToner", DbType="Int NOT NULL")]
		public int NewRemainToner
		{
			get
			{
				return this._NewRemainToner;
			}
			set
			{
				if ((this._NewRemainToner != value))
				{
					this._NewRemainToner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelBlack", DbType="Int")]
		public System.Nullable<int> MaxLevelBlack
		{
			get
			{
				return this._MaxLevelBlack;
			}
			set
			{
				if ((this._MaxLevelBlack != value))
				{
					this._MaxLevelBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainBlack", DbType="Int")]
		public System.Nullable<int> RemainBlack
		{
			get
			{
				return this._RemainBlack;
			}
			set
			{
				if ((this._RemainBlack != value))
				{
					this._RemainBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargeDate", DbType="Date")]
		public System.Nullable<System.DateTime> ChargeDate
		{
			get
			{
				return this._ChargeDate;
			}
			set
			{
				if ((this._ChargeDate != value))
				{
					this._ChargeDate = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_RemainDays2Result
	{
		
		private string _BranchNumber;
		
		private string _Model;
		
		private string _SerialNumber;
		
		private string _IPAddress;
		
		private int _NewRemainToner;
		
		private System.Nullable<int> _MaxLevelBlack;
		
		private System.Nullable<int> _RemainBlack;
		
		private System.Nullable<System.DateTime> _ChargeDate;
		
		public sp_SEL_RemainDays2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchNumber", DbType="NVarChar(20)")]
		public string BranchNumber
		{
			get
			{
				return this._BranchNumber;
			}
			set
			{
				if ((this._BranchNumber != value))
				{
					this._BranchNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(50)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewRemainToner", DbType="Int NOT NULL")]
		public int NewRemainToner
		{
			get
			{
				return this._NewRemainToner;
			}
			set
			{
				if ((this._NewRemainToner != value))
				{
					this._NewRemainToner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelBlack", DbType="Int")]
		public System.Nullable<int> MaxLevelBlack
		{
			get
			{
				return this._MaxLevelBlack;
			}
			set
			{
				if ((this._MaxLevelBlack != value))
				{
					this._MaxLevelBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainBlack", DbType="Int")]
		public System.Nullable<int> RemainBlack
		{
			get
			{
				return this._RemainBlack;
			}
			set
			{
				if ((this._RemainBlack != value))
				{
					this._RemainBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargeDate", DbType="Date")]
		public System.Nullable<System.DateTime> ChargeDate
		{
			get
			{
				return this._ChargeDate;
			}
			set
			{
				if ((this._ChargeDate != value))
				{
					this._ChargeDate = value;
				}
			}
		}
	}
	
	public partial class sp_SEL_TONERResult
	{
		
		private string _BranchNumber;
		
		private string _SerialNumber;
		
		private string _model;
		
		private string _IPAddress;
		
		private System.Nullable<int> _PageCount;
		
		private System.Nullable<int> _ReplaceCount;
		
		private System.Nullable<int> _MaxLevelBlack;
		
		private System.Nullable<int> _RemainBlack;
		
		private System.Nullable<int> _PercentBlack;
		
		private System.Nullable<int> _MaxLevelCyan;
		
		private System.Nullable<int> _RemainCyan;
		
		private System.Nullable<int> _PercentCyan;
		
		private System.Nullable<int> _MaxLevelMagenta;
		
		private System.Nullable<int> _RemainMagenta;
		
		private System.Nullable<int> _PercentMagenta;
		
		private System.Nullable<int> _MaxLevelYellow;
		
		private System.Nullable<int> _RemainYellow;
		
		private System.Nullable<int> _PercentYellow;
		
		private System.DateTime _LastUpdate;
		
		public sp_SEL_TONERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchNumber", DbType="NVarChar(20)")]
		public string BranchNumber
		{
			get
			{
				return this._BranchNumber;
			}
			set
			{
				if ((this._BranchNumber != value))
				{
					this._BranchNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this._SerialNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(50)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this._model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(50)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageCount", DbType="Int")]
		public System.Nullable<int> PageCount
		{
			get
			{
				return this._PageCount;
			}
			set
			{
				if ((this._PageCount != value))
				{
					this._PageCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplaceCount", DbType="Int")]
		public System.Nullable<int> ReplaceCount
		{
			get
			{
				return this._ReplaceCount;
			}
			set
			{
				if ((this._ReplaceCount != value))
				{
					this._ReplaceCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelBlack", DbType="Int")]
		public System.Nullable<int> MaxLevelBlack
		{
			get
			{
				return this._MaxLevelBlack;
			}
			set
			{
				if ((this._MaxLevelBlack != value))
				{
					this._MaxLevelBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainBlack", DbType="Int")]
		public System.Nullable<int> RemainBlack
		{
			get
			{
				return this._RemainBlack;
			}
			set
			{
				if ((this._RemainBlack != value))
				{
					this._RemainBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PercentBlack", DbType="Int")]
		public System.Nullable<int> PercentBlack
		{
			get
			{
				return this._PercentBlack;
			}
			set
			{
				if ((this._PercentBlack != value))
				{
					this._PercentBlack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelCyan", DbType="Int")]
		public System.Nullable<int> MaxLevelCyan
		{
			get
			{
				return this._MaxLevelCyan;
			}
			set
			{
				if ((this._MaxLevelCyan != value))
				{
					this._MaxLevelCyan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainCyan", DbType="Int")]
		public System.Nullable<int> RemainCyan
		{
			get
			{
				return this._RemainCyan;
			}
			set
			{
				if ((this._RemainCyan != value))
				{
					this._RemainCyan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PercentCyan", DbType="Int")]
		public System.Nullable<int> PercentCyan
		{
			get
			{
				return this._PercentCyan;
			}
			set
			{
				if ((this._PercentCyan != value))
				{
					this._PercentCyan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelMagenta", DbType="Int")]
		public System.Nullable<int> MaxLevelMagenta
		{
			get
			{
				return this._MaxLevelMagenta;
			}
			set
			{
				if ((this._MaxLevelMagenta != value))
				{
					this._MaxLevelMagenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainMagenta", DbType="Int")]
		public System.Nullable<int> RemainMagenta
		{
			get
			{
				return this._RemainMagenta;
			}
			set
			{
				if ((this._RemainMagenta != value))
				{
					this._RemainMagenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PercentMagenta", DbType="Int")]
		public System.Nullable<int> PercentMagenta
		{
			get
			{
				return this._PercentMagenta;
			}
			set
			{
				if ((this._PercentMagenta != value))
				{
					this._PercentMagenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevelYellow", DbType="Int")]
		public System.Nullable<int> MaxLevelYellow
		{
			get
			{
				return this._MaxLevelYellow;
			}
			set
			{
				if ((this._MaxLevelYellow != value))
				{
					this._MaxLevelYellow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainYellow", DbType="Int")]
		public System.Nullable<int> RemainYellow
		{
			get
			{
				return this._RemainYellow;
			}
			set
			{
				if ((this._RemainYellow != value))
				{
					this._RemainYellow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PercentYellow", DbType="Int")]
		public System.Nullable<int> PercentYellow
		{
			get
			{
				return this._PercentYellow;
			}
			set
			{
				if ((this._PercentYellow != value))
				{
					this._PercentYellow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this._LastUpdate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
